FROM alpine

RUN apk update
RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community go=1.18.2-r0

ENV PATH /go/bin:$PATH

WORKDIR app

COPY . .

RUN go mod tidy

EXPOSE 9000
ENV HOST 0.0.0.0

CMD ["go", "run", "app/main.go", "app/db.go"]
